baseURL = 'https://ctuck.com/'
title = 'ctuck.com'
paginate = 5
languageCode = 'en-us'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

outputs.home = ['HTML', 'RSS', 'JSON']

[[menu.main]]
identifier = 'resume'
name = 'Resumé'
url = '/resume'
weight = 20

[params]
env = 'production'
description = "Cameron Tuckerman-Lee's Personal Site"
disableThemeToggle = true
defaultTheme = 'light'
socialIcons = [
  { name = 'email', url = 'mailto:cameron@ctuck.com' },
  { name = 'github', url = 'https://github.com/tuckerman' },
  { name = 'mastodon', url = 'https://mastodon.social/@tuckerman' },
  { name = 'twitter', url = 'https://twitter.com/tuckerman' },
  { name = 'rss', url = 'index.xml' },
]
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true


[params.profileMode]
enabled = true
title = 'Cameron Tuckerman-Lee'
subtitle = "Hi there! I'm a software engineer interested in the intersection of AI, Robotics, and Large-Scale Distributed Systems. I'm currently at Wayve and have previously have worked at Google, X (the moonshot factory), and Airbnb. I'm mostly made of coffee."
imageUrl = 'profile.jpg'
buttons = [
  { name = 'Posts', url = 'posts' },
  { name = 'Tags',  url = 'tags' },
]
